### ISSUE TITLE
Install last version installation.html#install-on-vps

### ISSUE THREAD

**Issue by xr0m3oz** [vitodeploy/vito#265] opened 2024-08-01 15:16 UTC
**Describe the bug**
Cant login with credentials, error These credentials do not match our records.

**To Reproduce**
1. Instal on fresh server
2. login not work

**Comment by saeedvaziry** [comment] 2024-08-01 16:17
I just installed from scratch on a VPS and logged in. works fine.

**Comment by xr0m3oz** [comment] 2024-08-01 17:51
Tried 2 times, copied login password

**Comment by xr0m3oz** [comment] 2024-08-01 17:52
Now I installed it via Docker, but I noticed that the logs are not displayed. The window with logs is empty if you click on the view icon. And all the logs.

**Comment by xr0m3oz** [comment] 2024-08-01 17:52
![Uploading SCR-20240801-szo.png…]()

**Comment by xr0m3oz** [comment] 2024-08-01 17:53
![SCR-20240801-szo](https://github.com/user-attachments/assets/17a3723d-fe48-498f-9734-3d16ddbbea2b)

**Comment by xr0m3oz** [comment] 2024-08-01 17:54
And another question, if installed via Docker, where on the server does it store website files?

**Comment by xr0m3oz** [comment] 2024-08-01 17:57
![Uploading SCR-20240801-t36.png…]()

**Comment by saeedvaziry** [comment] 2024-08-01 22:02
Maybe the log is empty. does it show empty for every log?

**Comment by xr0m3oz** [comment] 2024-08-02 15:39
yes, all logs

**Comment by saeedvaziry** [comment] 2024-08-03 09:28
Using docker myself but can't reproduce. the 302 HTTP status is irrelevant here because HTMX sends a request and then server redirects with the content of the log into the headers.

**Comment by saeedvaziry** [comment] 2024-08-04 07:44
please share the docker-compose file or the docker command you run to boot vito up

**Comment by xr0m3oz** [comment] 2024-08-04 10:52
`
version: "3"
services:
  vito:
    image: vitodeploy/vito:latest
    ports:
      - "8000:80"
    environment:
      APP_KEY: "base64:JseLbT+BkJJTfkbAV8bdihJ+Fo9g4/Db/fsuGsv4Z0c="
      NAME: "vito"
      EMAIL: "xr0m3oz@gmail.com"
      PASSWORD: "554554"
    volumes:
      - "vito-storage:/var/www/html/storage"
volumes:
  vito-storage:
    driver: local
`

**Comment by algsupport** [comment] 2024-08-22 07:27
I was able to reproduce the issue on a VPS installation.

When deploying a new server, the current running task will have empty logs, but all the completed ones show the logs ok.

**Comment by xr0m3oz** [comment] 2024-08-22 07:31
All the logs were not displayed for me.  both at runtime and all the old
ones that could be opened later.

чт, 22 авг. 2024 г., 10:28 ALGSUPPORT OÜ ***@***.***>:

**Comment by saeedvaziry** [comment] 2024-08-22 15:53
> When deploying a new server, the current running task will have empty logs, but all the completed ones show the logs ok

@algsupport this is something to consider if we can improve, for example having logs streamed to the log files so they can be readable even during the command execution

**Comment by xr0m3oz** [comment] 2024-08-23 20:32
In the forge service, the log is visible online during execution. I think
you can do the same.

чт, 22 авг. 2024 г., 18:53 Saeed Vaziry ***@***.***>:

**Comment by saeedvaziry** [comment] 2024-11-01 20:31
We'll need to stream the logs and not wait for them to finish.

Closing the current issue as its not a bug

**Closed by saeedvaziry** 2024-11-01 20:31 UTC
Labels: bug
