### ISSUE TITLE
Invalid datetime format: 1292 Incorrect datetime value: '' for column 'expires_at' at row 1

### ISSUE THREAD

**Issue by devappsoftware** [vitodeploy/vito#121] opened 2024-03-18 10:12 UTC
**Describe the bug**
When installing a cloud flare certificate with a 15 year expiry date:

**To Reproduce**
Paste in the certificate and private key. A 500 error is shown.

```

[previous exception] [object] (PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'expires_at' at row 1 at /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php:580)
[stacktrace]
#0 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): PDOStatement->execute()
#1 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php(809): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php(776): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\\Database\\Connection->run()
#4 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->statement()
#5 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#6 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3387): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#7 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1968): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1333): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1298): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1137): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /home/vito/apps.applicationmate.io/app/Models/Site.php(325): Illuminate\\Database\\Eloquent\\Model->save()
#12 /home/vito/apps.applicationmate.io/app/Actions/SSL/CreateSSL.php(25): App\\Models\\Site->createCustomSsl()
#13 /home/vito/apps.applicationmate.io/app/Http/Livewire/Ssl/CreateSsl.php(24): App\\Actions\\SSL\\CreateSSL->create()
#14 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\Ssl\\CreateSsl->create()
#15 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#17 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#18 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/Wrapped.php(23): Illuminate\\Container\\BoundMethod::call()
#19 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(467): Livewire\\Wrapped->__call()
#20 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(99): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->callMethods()
#21 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->update()
#22 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(86): Livewire\\LivewireManager->update()
#23 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Mechanisms\\HandleRequests\\HandleRequests->handleUpdate()
#24 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#25 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#26 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#27 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#28 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#43 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#45 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#47 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /home/vito/apps.applicationmate.io/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#50 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#52 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#60 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#62 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#64 /home/vito/apps.applicationmate.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 /home/vito/apps.applicationmate.io/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 {main}
"} 
```

**Comment by devappsoftware** [comment] 2024-03-18 10:21
Seems the value is being set to '' in the code, rather than dynamic:

```
    public function createCustomSsl(string $certificate, string $pk): void
    {
        $ssl = new Ssl([
            'site_id' => $this->id,
            'type' => 'custom',
            'certificate' => $certificate,
            'pk' => $pk,
            'expires_at' => '2035-01-01 00:00:00',
            'status' => SslStatus::CREATING,
        ]);
        $ssl->save();
        $ssl->deploy();
    }
```

If I set manually as above it works, but then other errors. Seems it is trying to execute the certificate:

```

-----BEGIN CERTIFICATE-----
bash: line 6: AgIUGdJvvKLLSkBQKrZ9LrxGOb746IYwDQYJKoZIhvcNAQEL: command not found
bash: line 7: NVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw: command not found
bash: line 8: bG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y: command not found
bash: line 9: HEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh: command not found
```

**Comment by saeedvaziry** [comment] 2024-03-18 10:41
@devappsoftware I will try to reproduce it but from the info you shared looks like its a bug.

**Comment by devappsoftware** [comment] 2024-03-18 11:05
Thanks. Second issue seems to happen because of \n (line endings) in certificate pasted in - When I remove \n it does, so maybe a helper function to strip the new lines out? 

When removed, it then creates:

```
if ! sudo mkdir -p __path__; then
    echo 'VITO_SSH_ERROR' && exit 1
fi

if ! echo __certificate__ | sudo tee __certificate_path__; then
    echo 'VITO_SSH_ERROR' && exit 1
fi

if ! echo __pk__ | sudo tee __pk_path__; then
    echo 'VITO_SSH_ERROR' && exit 1
fi

echo "Successfully received certificate."
```

**Comment by devappsoftware** [comment] 2024-03-18 11:13
Needs the line breaks or nginx won't start.

```
Mar 18 11:11:32 issac systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 18 11:11:32 issac nginx[31677]: nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in >
Mar 18 11:11:32 issac nginx[31677]: nginx: [emerg] cannot load certificate "/etc/ssl/xxxx/cert.pem": PEM_rea>
Mar 18 11:11:32 issac nginx[31677]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

After pasting manually, it starts again.

**Comment by saeedvaziry** [comment] 2024-03-18 14:17
@devappsoftware so Vito doesn't write the certificate properly into the files?

This is not related to the expire_date issue, right?

**Comment by saeedvaziry** [comment] 2024-03-18 16:12
@devappsoftware The PR will fix the issue. but the fix will apply on version 1.x which I am planning to release it this weekend.

**Comment by devappsoftware** [comment] 2024-03-18 19:02
Hi again,

2 seperate issues, but both related to the workflow of adding a custom SSL certificate.

**Comment by saeedvaziry** [comment] 2024-03-18 19:03
@devappsoftware both fixed in the PR.

**Closed by saeedvaziry** 2024-03-18 19:03 UTC
Labels: bug
